require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Hardcore Initiated",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Credits To Ping,Noonie And Chrono",true)
wait(2) require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Doors Impossible Hardcore Mayhem Remnant Mode🤑👍🏼",true)
-- Seek Redesign 
loadstring(game:HttpGet('https://raw.githubusercontent.com/StovenChaos/Doors/main/Old%20seek.lua'))()

-- Seek Music
coroutine.wrap(function()
function GitAud(soundgit,filename)
    SoundName=tostring(SoundName)
    local url=soundgit
    local FileName = filename
    writefile(FileName..".mp3", game:HttpGet(url))
    return (getcustomasset or getsynasset)(FileName..".mp3")
end

function CustomGitSound(soundlink, vol, filename)
    local Sound = Instance.new("Sound")
    Sound.SoundId = GitAud(soundlink, filename)
    Sound.Parent = workspace
    Sound.Volume = 0
    Sound:Play()
end

CustomGitSound("https://github.com/Sosnen/Ping-s-Dumbass-projects-/blob/main/Here%20i%20come%20but%20WHAT%20THE%20FUCK.mp3?raw=true", 1, "Hereicomeseekog")

local function GetGitSoundID(GithubSnd,SoundName)
		SoundName=tostring(SoundName)
		local url=GithubSnd
		SoundName=tostring(SoundName)
		local url=GithubSnd
		FileName = SoundName
		writefile("customObject_Sound_"..FileName..".mp3", game:HttpGet(url))
		return (getcustomasset or getsynasset)("customObject_Sound_"..FileName..".mp3")
	end
end)()

--Optional Seek Eyes it might lag your device
coroutine.wrap(function()
    while true do
        wait(0.0005)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0.0005)
        local ohmygah = Instance.new("Folder")
        ohmygah.Parent = workspace.CurrentRooms[game.ReplicatedStorage.GameData.LatestRoom.Value]
    end
end)()

-- Sprint Bar
loadstring(game:HttpGet("https://raw.githubusercontent.com/MuhXd/DoorSuff/main/OtherSuff/Sprint"))()

-- Cease
coroutine.wrap(function()
    while true do
        wait(200)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastefy.app/ofutwkjb/raw"))()
    
end
               
end)()

-- shocker
coroutine.wrap(function()
    while true do
        wait(35)
        loadstring(game:HttpGet("https://raw.githubusercontent.com/vct0721/Doors-Stuff/refs/heads/main/Entities/Shocker"))()
end

end)()

-- Dread
coroutine.wrap(function()
    while true do
        wait(550)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)       
loadstring(game:HttpGet("https://raw.githubusercontent.com/huyhoanggphuc/Entity-obfuscate/refs/heads/main/Dread.lua"))()

end
               
end)()

-- a-60
coroutine.wrap(function()
    while true do
        wait(600)
         game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
loadstring(game:HttpGet("https://pastebin.com/raw/KpqhHcyx"))()
 
end
 
end)()

-- Silence
coroutine.wrap(function()
    while true do
        wait(440)
         game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/uNnkcsGU"))()

end
    
end)()

-- Rebound
coroutine.wrap(function()
    while true do
        wait(150)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet('https://raw.githubusercontent.com/Kotyara19k-Doorsspawner/Random-files/main/ReboundHardcoreSpawn'))()

end

end)()

-- A200(Secret Entity)
coroutine.wrap(function()
    while true do
        wait(100000)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
        loadstring(game:HttpGet('https://pastefy.app/1xxpTxo3/raw'))()

        end

        end)()

-- A90
coroutine.wrap(function()
    while true do
        wait(150)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastebin.com/raw/DsS87QeW"))()

end

end)()

--Frostbite
coroutine.wrap(function()
wait(160)
game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
loadstring(game:HttpGet("https://pastefy.app/Zb1au2BU/raw"))()

end

end)()

-- Ripper
coroutine.wrap(function()
    while true do
        wait(108)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://raw.githubusercontent.com/huyhoanphuc/testhshs/refs/heads/main/hshsbsbshripper"))(

end 

end)()

-- Deer God
coroutine.wrap(function()
    while true do
        wait(230)
        game.ReplicatedStorage.GameData.LatestRoom.Changed:Wait()
        wait(0)
loadstring(game:HttpGet("https://pastefy.app/17nNEGQe/raw"))()

end

end)()
